### ISSUE TITLE
I want to increase the number of bits send to the mobile app currently it reads data from 0 to ff?

### ISSUE THREAD

**Issue by melwyngit** [bjornspockeli/custom_ble_service_example#5]
By using the notifications characteristics/service i can upload only data from 00 to ff.I want to upload data from 00 to 64000 atleast. i tried changing the data type from uint_8 to uint_32 but it does not work

**Comment by bjornspockeli** [comment]
BLE characteristic only deals with octets or arrays of octets, i.e. byte-streams. If you're sending something bigger than a byte, then you need to format the data so that it can be placed in a byte array. 

So if you want to sent a 32-bit unsigned integer, then you will have to set the size of the characteristic to 4*sizeof(uint8_t) and then divide the 32-bit integer into four 8-bit usigned integers, e.g. 

```
uint32_t large_number = 64000;
uint8_t ble_data[4] = {0};
 
for(int i = 0; i < sizeof(ble_data);i++)
{
    ble_data[i] = large_number >> (i*8);
}
```
On the central side you will have to reassemble the 32-bit integer from the notified data array
                               
Array index       [       0         |          1       |         2       |      3      ]
Array elements [ Bits 31- 24| Bits 23- 16 | Bits 15 -8 | Bits 7-0 ]
